CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(100),
	forename VARCHAR(50),
	surname VARCHAR(50),
	locale VARCHAR(20),
	groups VARCHAR(20)[],
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userauth (
	id SERIAL PRIMARY KEY,
	userid SERIAL REFERENCES users(id),
	hash VARCHAR(100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);